spring.datasource.url=jdbc:mysql://localhost:3306/spsecurity
spring.datasource.username=root
spring.datasource.password=india1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect.storage_engine=innodb
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.security.user.name = Sudeep
#spring.security.user.password = india123
